name: bmrl
channels:
  - defaults
dependencies:
  - python==3.8
  - pyopengl
  - pytorch==1.6
  - matplotlib
  - pandas
  - numpy
  - tqdm
  - jupyter
  - seaborn
  - scikit-learn
  - pip
  - pip:
    - gym==0.23.1
    - pygame==2.1.2
